# Generated by Django 5.0.7 on 2024-07-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0002_alter_transformeddata_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad_nominal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TransformedData',
        ),
    ]
