# Generated by Django 5.0.7 on 2024-07-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0003_newdata_delete_transformeddata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newdata',
            table='djangoRestApp_newdata',
        ),
        migrations.AlterModelTable(
            name='rawdata',
            table='raw_data',
        ),
    ]
